name: rancher-components
on:
  pull_request:
    paths:
      - 'pkg/rancher-components/**/*'
    branches:
      - master

jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
<<<<<<< HEAD
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
=======
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
>>>>>>> b7384b5fad (Revert "script adjustment/fix")
      
      - name: Install packages
        run: yarn install

      - name: Verify build
        run: yarn build:lib

  validate-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
<<<<<<< HEAD
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
=======
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
>>>>>>> b7384b5fad (Revert "script adjustment/fix")
      
      - name: Install packages
        run: yarn install
      
      - name: Run linters
        run: yarn lint:lib
