name: Build and Publish Rancher Components

on:
  push:
    tags:
        - 'components-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false

<<<<<<< HEAD
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
=======
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
>>>>>>> b7384b5fad (Revert "script adjustment/fix")
        registry-url: 'https://registry.npmjs.org'
        scope: '@rancher'

    - name: Install
      run: yarn install:ci

    - name: Lint
      run: yarn lint:lib

    - name: Build
      run: yarn build:lib

    - name: Unit Test
      run: yarn test:ci ./pkg/rancher-components

    - name: Publish to npm
      run: yarn publish:lib
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
