<<<<<<< HEAD
name: storybook
env:
    STORYBOOK_TOKEN: ${{ secrets.STORYBOOK_TOKEN }}
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
<<<<<<< HEAD
        node-version-file: '.nvmrc'
=======
        node-version: '16.20.2'
>>>>>>> b7384b5fad (Revert "script adjustment/fix")
    - name: Install packages
      run: yarn install
    - name: Build Storybook
      run: |
        yarn build-storybook
    - name: Publish Storybook
      if: ${{ github.event_name == 'push' && github.repository_owner == 'rancher'}}
      run: .github/workflows/scripts/publish-storybook
=======
# name: storybook
# env:
#     STORYBOOK_TOKEN: ${{ secrets.STORYBOOK_TOKEN }}
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master
# jobs:
#   storybook:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Use Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '16.20.2'
#     - name: Install packages
#       run: yarn install
#     - name: Build Storybook
#       run: |
#         yarn build-storybook
#     - name: Publish Storybook
#       if: ${{ github.event_name == 'push' && github.repository_owner == 'rancher'}}
#       run: .github/workflows/scripts/publish-storybook
>>>>>>> 25d643d2d3 (comment workflows)
