name: Test Extension workflows

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 12032-reusable-wf-tests-2
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  test:
    uses: aalves08/dashboard/.github/workflows/build-extension-charts.yml@12032-reusable-wf-tests-2
    permissions:
      actions: write
      contents: write
      deployments: write
      pages: write
    with:
      target_branch: 'gh-pages'
      tagged_release:  'clock-0.3.2'
      is_test:  'true'
      test_repo: 'ui-plugin-examples'
      test_branch:  'main'