name: Test Extension workflows

on:
  push:
    branches:
      - 12032-reusable-wf-tests-2
  # schedule:
  #   - cron: "0 0 * * *"

defaults:
  run:
    shell: bash
    working-directory: ./
jobs:
  retrieve-tags-master:
    runs-on: ubuntu-latest
    outputs:
      SHELL_TAG: ${{ steps.retrieve-data.outputs.SHELL_TAG }}
      CREATORS_TAG: ${{ steps.retrieve-data.outputs.CREATORS_TAG }}
      ECI_TAG: ${{ steps.retrieve-data.outputs.ECI_TAG }}
      EXTENSIONS_TAG: ${{ steps.retrieve-data.outputs.EXTENSIONS_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve Shell and Creators versions
        run: source ./shell/scripts/retrieve-versions.sh
        id: retrieve-data
        shell: bash
  test-build-extension-charts-master:
    needs: retrieve-tags-master
    uses: aalves08/dashboard/.github/workflows/build-extension-charts.yml@12032-reusable-wf-tests-2
    permissions:
      actions: write
      contents: write
      deployments: write
      pages: write
    with:
      target_branch: 'gh-pages'
      tagged_release:  ${{ needs.retrieve-tags-master.outputs.EXTENSIONS_TAG }}
      is_test:  'true'
      test_repo: 'ui-plugin-examples'
      test_branch:  'main'
  test-build-extension-catalog-master:
    needs: retrieve-tags-master
    uses: aalves08/dashboard/.github/workflows/build-extension-catalog.yml@12032-reusable-wf-tests-2
    permissions:
      actions: write
      contents: read
      packages: write
    with:
      registry_target: ghcr.io
      registry_user: ${{ github.actor }}
      tagged_release: ${{ needs.retrieve-tags-master.outputs.ECI_TAG }}
      is_test:  'true'
      test_repo: 'ui-plugin-examples'
      test_branch:  'main'
    secrets: 
      registry_token: ${{ secrets.GITHUB_TOKEN }}
  test-release-shell-pkg-master:
    needs: retrieve-tags-master
    uses: aalves08/dashboard/.github/workflows/release-shell-pkg.yaml@12032-reusable-wf-tests-2
    with:
      is_test:  'true'
      test_branch:  '12032-reusable-wf-tests-2'
      tag: ${{ needs.retrieve-tags-master.outputs.SHELL_TAG }}
  test-release-creators-pkg-master:
    needs: retrieve-tags-master
    uses: aalves08/dashboard/.github/workflows/release-shell-pkg.yaml@12032-reusable-wf-tests-2
    with:
      is_test: 'true'
      test_branch: '12032-reusable-wf-tests-2'
      tag: ${{ needs.retrieve-tags-master.outputs.CREATORS_TAG }}