name: Test Extension workflows

on:
  push:
    branches:
      - 12032-reusable-wf-tests-2
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  test-build-extension-charts:
    uses: aalves08/dashboard/.github/workflows/build-extension-charts.yml@12032-reusable-wf-tests-2
    permissions:
      actions: write
      contents: write
      deployments: write
      pages: write
    with:
      target_branch: 'gh-pages'
      tagged_release:  'clock-0.3.2'
      is_test:  'true'
      test_repo: 'ui-plugin-examples'
      test_branch:  'main'
  test-build-extension-catalog:
    uses: aalves08/dashboard/.github/workflows/build-extension-catalog.yml@12032-reusable-wf-tests-2
    permissions:
      actions: write
      contents: read
      packages: write
    with:
      registry_target: ghcr.io
      registry_user: ${{ github.actor }}
      tagged_release:  'ui-plugin-examples-0.1.0'
      is_test:  'true'
      test_repo: 'ui-plugin-examples'
      test_branch:  'main'
    secrets: 
      registry_token: ${{ secrets.GITHUB_TOKEN }}